name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: 1351055318
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: 1351055318
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'green'
          color_snake: "#43cea2"
          color_dots: "#4776e6,#1e2d3d,#1e2d3d,#1e2d3d,#4776e6"

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
